### ISSUE TITLE
upload Gruntled to the Play Store (w/ limited functionality)

### ISSUE THREAD

**Issue by borntonguyen** [the-gruntled-company/Gruntled#105]
7/20 was the first time I submitted
It failed due to description not being long enough.

**Comment by cvraut** [comment]
@borntonguyen submitted app to store 07/20

**Comment by cvraut** [comment]
07/20 application was rejected:
![image](https://user-images.githubusercontent.com/10603882/180890601-5f5a1f6c-6866-451c-8690-98bca774723b.png)

**Comment by cvraut** [comment]
@borntonguyen extended description to make longer

then resubmitted on 07/25

**Comment by cvraut** [comment]
current description:

"Gruntled is reaction-sharing & consolidating Chrome extension for YouTube. Users are able to watch and react to a particular YouTube video, generate a link to send to their friends that will consolidate their reactions to the respective video. 


The result is a reaction video; two friends' reactions stitched alongside the watching video.


Take out the editing work & download Gruntled!
"

**Comment by cvraut** [comment]
Original description that failed: browser extension to consolidate user reactions to watching videos.
